# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  WS_CHECKPOLICIES=true: 'true'
  WS_FORCECHECKALLDEPENDENCIES: 'true'

steps:
- script: |
   curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
   echo Unified Agent downloaded successfully
   set
   java -jar wss-unified-agent.jar -apiKey 1234567 
  displayName: 'Mend Unified Agent Scan'