# Maven
task: CmdLine
  inputs:
    - script: |
        curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
        echo Unified Agent downloaded successfully
        set WS_CHECKPOLICIES=true
        set WS_FORCECHECKALLDEPENDENCIES=true
        java -jar wss-unified-agent.jar
      displayName: 'Mend Unified Agent Scan'

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

- trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

